version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: eval_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: eval_db
      POSTGRES_USER: eval_user
      POSTGRES_PASSWORD: eval_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./analytics/dbt/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
